### ISSUE TITLE
Set up read the docs to generate docs on commit to main

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/carbon-txt-validator#5]
For this to work we want to set it up with read the docs.

Either something like this:

```yaml
version: 2

   build:
      os: ubuntu-lts-latest
      tools:
         python: latest

   sphinx:
      configuration: docs/conf.py

```

Or if we're using uv, something like this:

```yaml
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync  --frozen
    - uv run sphinx-build docs docs/_build/html
```

The uv option is consistent with our use of uv for managing dependencies, but I've never used it with RTD.

https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
